{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "name" . }}
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    app: {{ template "name" . }}
{{- end }}