{{- $serviceName := include "nginx-ingress.name" . -}}
{{- if or .Values.controller.config (or (or .Values.controller.proxySetHeaders .Values.controller.headers) .Values.controller.addHeaders) }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "nginx-ingress.name" . }}
  name: {{ template "nginx-ingress.controller.fullname" . }}
  namespace: {{ .Values.global.namespace }}
data:
{{- if .Values.controller.addHeaders }}
  add-headers: {{ .Values.global.namespace }}/custom-headers
{{- end }}
{{- if or .Values.controller.proxySetHeaders .Values.controller.headers }}
  proxy-set-headers: {{ .Values.global.namespace }}/custom-proxy-headers
{{- end }}
{{- if .Values.controller.config }}                                   
  {{- tpl .Values.controller.config . | nindent 2 }}
{{- end }}
{{- end }}