apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  externalName: {{ .Values.externalName }}
  ports:
  - port: {{ .Values.httpPort }}
    protocol: TCP
    targetPort: {{ .Values.httpPort }}
  sessionAffinity: None
  type: {{ .Values.type }}

