apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digit-user
rules:
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - pods/portforward
  - pods/proxy 
  verbs:
  - create  
  - delete
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: digit-admin
rules:
- apiGroups: ["apps", "extensions"]  
  resources: ["deployments", "ingresses"] 
  verbs: ["patch", "create", "delete", "get", "list", "update"]
- apiGroups: [""]
  resources: ["services", "endpoints", "pods", "configmaps", "secrets"]
  verbs: ["get", "watch", "create", "delete", "update", "list", "patch"]    
- apiGroups: [""]
  resources: ["pods/portforward" , "pods/proxy", "pods/exec"] 
  verbs: ["create", "delete"]
