apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "common.name" . }}
  name: {{ template "common.name" . }}
  namespace: {{ .Values.global.namespace }}  
data:
  oauth2_proxy.cfg: {{ .Values.config.configFile | quote }}
